version: "3.1"

services:
    mongo:
        container_name: database
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    app:
        container_name: app
        image: chat/app
        build: .
        restart: always
        ports:
            - 8081:8081
        environment:
            PORT: 8081
            NODE_ENV: production
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            JWT_SECRET_TOKEN: 123456
            DB_NAME: chatapp
            DB_URI: mongodb://root:example@mongo:27017/
